### ISSUE TITLE
Enable HTTPS

### ISSUE THREAD

**Issue by simnalamburt** [upnl/work#1]
Let's encrypt 쓰면 돈 한푼 안쓰고 할수있고, 더이상 중전의 공격을 받지 않을 수 있음!

#### TODOs
- [x] uriel.upnl.org TLS 인증서 업데이트
- [x] upnl.org 에 HTTPS 적용
- [x] git.upnl.org 에 HTTPS 적용
- [x] pokemon.upnl.org 에 HTTPS 적용
- [x] 그 외 필요한 도메인들 더 찾아서 적용
- [x] 자동업데이트 넣기

#### 자동업데이트 넣는법

```bash
sudo crontab -e
```
```cron
30 2 * * 1 /usr/local/sbin/certbot-auto renew >> /var/log/le-renew.log
35 2 * * 1 /etc/init.d/nginx reload
```

~웹루트 인증을 쓸 수 있을경우 nginx 종료 없이 갱신이 가능하지만, 그렇지 못할경우 인증 전후에 nginx을 끄고 켜야한다.~ 이제 그냥 certbot nginx 플러그인을 쓰면 된다.

###### References
- https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-14-04
- https://github.com/VBChunguk/systemd-certbot-renew

**Comment by jc-kim** [comment]
https://uriel.upnl.org/

**Comment by simnalamburt** [comment]
헐쩐다

https://uriel.upnl.org/<사람이름>/ 도 지원합시다 와와

**Comment by jc-kim** [comment]
https://uriel.upnl.org/~jc/ 랑 https://uriel.upnl.org 는 같이 되는데
https://uriel.upnl.org/jc/ 이걸 되게 하려고 config를 바꾸면 https://uriel.upnl.org 가 404가 뜨네 끵
귀찮아[?] 여기까지 할래...

**Comment by jc-kim** [comment]
![image](https://cloud.githubusercontent.com/assets/892477/13865814/ef74adcc-ecf2-11e5-8f26-a64de2373081.png)
하하[?]

**Comment by simnalamburt** [comment]
[Caddy](https://caddyserver.com/)로 인증서 자동갱신까지 전부다 자동화하여 해결했음!!!!!

**Comment by pbzweihander** [comment]
Caddy를 이용해 홈페이지를 비롯한 제미니에서 돌아가는 모든 웹페이지에 https를 적용시켰습니다!!

**Comment by pbzweihander** [comment]
[![screenshot from 2018-05-07 22-37-26](https://user-images.githubusercontent.com/15262528/39704915-d4dd5560-5247-11e8-8931-fe46ecb06748.png)](https://www.ssllabs.com/ssltest/analyze.html?d=upnl.org&hideResults=on)
