### ISSUE TITLE
서버들에 RAM 늘리기

### ISSUE THREAD

**Issue by simnalamburt** [upnl/work#13]
램 그렇게 비싸지도 않은데, 유리엘과 소드락이 만성적인 램부족에 시달리고있습니다. 늘려줍시다 와와

- [x] ~~유리엘 DDR3 2GB × 1~~ &rarr; 폐기됨
- [x] 소드락 ~~DDR2 1GB × 2~~ &rarr; 2GB × 4 (업그레이드 완료)
- [x] 제미니 DDR2 1GB×2 + 2GB×2 (서비스가 많이 빠짐, 충분함)
- [x] 에델브로이 DDR3 4GB * 4 (충분함)

#### TODOs
램을 2GB × 8개 구입함

- [x] 4개 소드락 램 업그레이드하는데에 쓰기
- [x] ~~4개 유리엘 램 업그레이드하는데에 쓰기~~ &rarr; 유리엘 폐기됨

**Comment by kalaluthien** [comment]
구체적으로 얼마나 늘려야 하나요?

**Comment by simnalamburt** [comment]
모두 8기가로 바꾸면 될거같아요

**Comment by simnalamburt** [comment]
램을 2GB \* 8개 구입하였습니다. 4개는 소드락에 꽂았으며, 4개는 유리엘에 꽂을 예정입니다.

**Comment by simnalamburt** [comment]
업그레이드 완료
