### ISSUE TITLE
유피넬 공용 Cloudflare 계정 생성

### ISSUE THREAD

**Issue by simnalamburt** [upnl/work#29]
지금 유피넬 cloudflare는 김지현의 개인계정으로 관리되고있는데, https://github.com/upnl/work/issues/9 가 해결되고나면 유피넬 공용 Cloudflare 계정을 만들 수 있다.

**Comment by simnalamburt** [comment]
원래는 upnl@upnl.org 계정으로 클라우드플레어에 가입 한 뒤 pbzweihander@upnl.org tirr@upnl.org simnalamburt@upnl.org 를 직원으로 추가해서 여러 서버관리자가 DNS를 공동관리하려고 했습니다.

그러나 upnl.org에 달려있는 G Suite가 알고보니 무료체험판 끝난 못쓸물건이라는걸 알았으니 (#32) 다른 방안을 떠올려야합니다

1. upnl.chairman@gmail.com 으로 클라우드플레어에 가입한 뒤, simnalamburt@gmail.com 등 각 서버관리자의 개인 이메일을 클라우드플레어에 추가한다
2. postfix를 깔든 메일건을 쓰든 어떻게어떻게 해서 @upnl.org 이메일을 부활시킨 뒤, 원안대로 upnl@upnl.org 로 가입한 뒤 simnalamburt@upnl.org tirr@upnl.org 등을 추가한다

CC @tirr-c @pbzweihander 

```
<@아얄클쯔방> 저는 1번이 나을거 같은데..
```

티르님께서도 의견 달아주세요

**Comment by tirr-c** [comment]
지금은 1번으로 가는 게 좋을 것 같아요

**Comment by simnalamburt** [comment]
1번으로 진행하겠습니다.

@pbzweihander <upnl.chairman@gmail.com>으로 클라우드플레어에 가입한 뒤, 아무것도 하지말고 (2FA 거시면 안됨) 저에게 그 클라우드플레어 계정의 임시 비밀번호를 알려주세요. 도메인 이전 작업 할게요.

**Comment by simnalamburt** [comment]
비밀번호 https://gist.github.com/pbzweihander/de3923882d042f0b7c8f2eb07a214be2/raw/1d957c7d82c00f99706a68044c885e70767fefba/some_text

**Comment by simnalamburt** [comment]
현재 upnl.org 네임서버는 아래와 같다.

- chan.ns.cloudflare.com
- earl.ns.cloudflare.com

이것을 아래와 같이 고쳐야 클라우드플레어 계정 이전이 가능하다.

- asa.ns.cloudflare.com
- ernest.ns.cloudflare.com

양쪽 계정 DNS 레코드는 정확히 일치하도록 설정해둔 상태이다. 네임서버만 바꾸면 된다. @jinurius 님의 도움이 필요함.

**Comment by simnalamburt** [comment]
### TODOs
- [x] 밧시님께서 네임서버 바꿔주시는것 기다리기
- 클라우드플레어 공용 계정에 세 서버관리자의 이메일 추가하기
  - [x] 김지현
  - [x] 티르
  - [x] 쯔방
- [x] 클라우드플레어 공용계정에 2FA 강제정책 켜기
- [x] 네임서버 바뀌는대로, 유리엘과 소드락 `/etc/init/caddy.conf` 에 박혀있는 클라우드플레어 크레덴셜 교체한 뒤, Caddy 서버 재시작하기

**Comment by jinurius** [comment]
@simnalamburt 네임서버 변경했습니다.

**Comment by simnalamburt** [comment]
@jinurius 끼요오 감사합니다

@pbzweihander 이 버튼 눌러조요

<img width="985" alt="a" src="https://user-images.githubusercontent.com/4435445/43688197-97ab7054-991f-11e8-94cf-32e119316a41.png">

**Comment by simnalamburt** [comment]
계정 이전 완료!
