### ISSUE TITLE
Caddy 패키지화하기

### ISSUE THREAD

**Issue by simnalamburt** [upnl/work#30]
지금 제미니, 유리엘, 소드락을 보면 `/usr/local/bin/caddy`에 caddy 바이너리가 손으로 설치되어있는데, 이러면 관리가 불가능하다. 지금 손으로 설치한것들은 어차피 업그레이드하면서 지운다고 쳐도, 업그레이드 한 뒤에는 캐디 패키지를 설치하고싶다.

https://github.com/miekg/caddy-debian 이걸 포크해서 직접 caddy 패키징을 하자. 

### TODOs
- [ ] Makefile을 도커로 대체하기
- [ ] 지금 저 Makefile은 pre-built caddy 바이너리를 손으로 가져와서 패키징하게되어있는데, caddy 바이너리 빌드하는 과정까지 전부 도커화한 뒤, build dependencies를 go로 지정하자
- [ ] systemd 유닛 파일, upstart 설정 파일 여러개 참고해서 베스트프랙티스 지키는 좋은 버전을 만들어보자. 지금 공식이 주는 caddy upstart 설정은 상당히 부실하다.
  - https://github.com/mholt/caddy/tree/master/dist/init
- [ ] gitlab-runner 참고해서 upstart와 systemd를 모두 지원하는 패키지를 원소스로 관리하는 요령도 익혀보자
  - https://github.com/gitlabhq/gitlab-runner/blob/9ade9673/Makefile#L54-L59
  - https://github.com/gitlabhq/gitlab-runner/tree/9ade9673/packaging
- [ ] 그 외에 데비안/우분투 패키징 가이드와 잘 패키징된 좋은 deb 패키지들을 보며, best practice들을 학습하고 좋은 패키지를 만들자

패키징 한 뒤 `.deb` 파일을 손으로 배포해도 되지만, https://packagecloud.io/pricing 이런데에 메일보내면 오픈소스 프로젝트는 무료로 호스팅해주기도 하는 것 같다.

###### References
- https://github.com/miekg/caddy-debian
- https://wiki.debian.org/Packaging#Introduction_to_Debian_Packaging

**Comment by simnalamburt** [comment]
Caddy까지 도커로 돌리기로 결정함. See https://github.com/upnl/work/issues/20

**Comment by simnalamburt** [comment]
제미니는 모든 서비스를 도커화하는게 목표니까 제미니는 상관없다고 쳐도, 유리엘이나 소드락같은경우는 모든 유저들의 홈디렉토리를 서빙해줘야하는데 모든 유저들 홈디렉토리를 싸그리 마운트할게 아닌이상 Caddy를 도커화하기 난해하다.

**Comment by simnalamburt** [comment]
Kubernetes로 옮기게되면서 Caddy 안쓰게됨

**Comment by simnalamburt** [comment]
sodrak에선 Caddy를 계속 쓰겠네요 죄송합니다
