### ISSUE TITLE
도메인 양도받기

### ISSUE THREAD

**Issue by simnalamburt** [upnl/work#31]
유피넬 메일을 만들고나서, 유피넬 명의로 도메인 소유권을 양도받아야한다. 지금은 정밧시님의 소유로 되어있음.

도메인 Registrar도 가급적이면 한국 서비스 말고 [namecheap](https://www.namecheap.com/), AWS Route53, [Google Domains](https://domains.google/) 셋중 하나였으면 좋겠다. 셋중에선 네임칩이 제일 싸보인다.

CC @jinurius

### TODOs
- [x] 레지스트라 결정 &rarr; 클라우드플레어 쓰기
- [x] 유피넬 회계용 신용카드 혹은 페이팔 계정 만들기
- [x] 클라우드플레어 레지스트라 얼리억세스 열리면 트랜스퍼 시작하기
- 클라우드플레어 후속설정 하기
  - [x] ~~도메인 락 걸기~~ &rarr; 그런기능 없는듯
  - [x] WHOIS 프라이버시 보호 걸기 &rarr; 자동으로 무조건 걸린다고 함 https://community.cloudflare.com/t/cloudflare-registrar-and-whois-privacy/36225/3
  - [x] 도메인 자동갱신 걸기 &rarr; 걸려있었음
  - [x] DNSSEC 걸기 &rarr; 걸음
- [x] 네임칩 계정 삭제하기

###### References
- https://github.com/upnl/work/issues/9
- https://whois.domaintools.com/upnl.org

**Comment by simnalamburt** [comment]
```
<@지현> 제가
<@지현> 고대디에서 네임칩으로 도메인 양도하는걸 한번 해봤는데
<@지현> 잘 되더라구요
<@지현> 근데 지금 upnl.org 는 닷네임 코리아인데
<@지현> 과연 한국기업도 잘 될지......
<@지현> 걱정입니다
```

티르님께서 가비아->네임칩 해보셨는데 잘되셨다고 하셨다.

**Comment by simnalamburt** [comment]
구글도메인은 한국인은 못쓰는듯 하다. 도메인 레지스트라는 네임칩 쓰기로 결정되었다.

**Comment by pbzweihander** [comment]
도메인을 이전받기 위해 일단 네임칩에서 upnl.chairman@gmai.com으로 upnl 계정을 만들었습니다.

비밀번호는 암호화하여 others.md에 적어놓았습니다. 서버관리자만이 복호화 가능합니다.

**Comment by simnalamburt** [comment]
https://www.cloudflare.com/products/registrar/ 얘도 좋아보이네여 최저가보장에 공짜 DNSSEC

**Comment by jinurius** [comment]
어떻게 할지 결정하신 후 제게 알려주시면 그대로 진행하도록 하겠습니다.

**Comment by simnalamburt** [comment]
사실 거진 결정은 되었는데 다들 바빠서 진행을 못하는ㄱ........

**Comment by simnalamburt** [comment]
계정은 적을수록 좋은거같아서 네임칩 계정을 만들고 그걸 따로 관리하는것보단, Cloudflare 레지스트라를 쓰는게 나을 것 같네요. Cloudflare 도메인 얼리액세스 신청했어요. 답변 오면 트랜스퍼 시작할게요.

<img width="878" alt="1" src="https://user-images.githubusercontent.com/4435445/48671080-3436d380-eb66-11e8-96a7-946f67275ca3.png">

**Comment by simnalamburt** [comment]
<img width="1087" alt="2018-12-24 12 45 46" src="https://user-images.githubusercontent.com/4435445/50390394-26cec380-077a-11e9-97bc-eec1471bc7dd.png">

트랜스퍼 가능해졌어요. 트랜스퍼 시작하기 전에 유피넬 회계용 신용카드 혹은 페이팔 계정 둘중하나를 만들어야해서 이거먼저 하겠습니다

**Comment by pbzweihander** [comment]
페이팔 계정 붙이고 정밧시님과 함께 작업해서 도메인 이전 진행 중입니다. 5일 정도 기다려보라고 하니 일단 며칠 지켜봅시다.

**Comment by jinurius** [comment]
@pbzweihander 닷네임에 걸려 있던 '도난방지 서비스'를 해제했습니다. lock이 걸려 있었다는 건 아마도 이것 같은데, 이제 진행이 될 것 같아요. 확인 부탁드립니다~

---

추가 내용: 제게 도메인 이전 승인 메일이 와서 승인을 했습니다. 제가 진행해야 할 부분은 아마도 완료가 된 것처럼 보이네요 ㅎㅎ

**Comment by pbzweihander** [comment]
![screenshot from 2019-01-28 16-04-16](https://user-images.githubusercontent.com/15262528/51819642-79ba0e80-2316-11e9-9e7a-8804f1fdad6b.png)

도메인 이전이 완료되었습니다!

**Comment by simnalamburt** [comment]
네임칩 계정도 삭제하고 닫아야할것같아여. 맨 위 이슈의 TODO 참고해주세여

**Comment by pbzweihander** [comment]
도메인 락은 자동으로 걸려있는거 같아요.

WHOIS privacy도 기본으로 자동 지원 되요.

도메인 자동갱신도 설정되어있습니다.

**Comment by pbzweihander** [comment]
네임칩 계정을 삭제해달라는 문의를 넣었습니다.

**Comment by pbzweihander** [comment]
![screenshot from 2019-01-31 16-18-48](https://user-images.githubusercontent.com/15262528/52037941-e9790500-2573-11e9-84f2-c2ca07d8e72a.png)

네임칩 계정 삭제가 완료되었습니다.

**Comment by simnalamburt** [comment]
감사합니다! 고생 많으셨어요
