### ISSUE TITLE
유피넬 깃헙 봇계정 만들기

### ISSUE THREAD

**Issue by simnalamburt** [upnl/work#48]
도커헙에서 UPnL Org를 만들었는데, 아래와 같은 문제가 있다. 지금은 @pbzweihander 의 계정이 링크되어있는데, 이러면 정작 @pbzweihander 본인이 본인의 도커헙 계정에 본인의 깃헙계정을 링크할 수 없다. 봇계정 만들자.

<img width="900" alt="2019-01-03 1 08 43" src="https://user-images.githubusercontent.com/4435445/50623484-bf72f980-0f59-11e9-8396-1576c8656969.png">

### TODOs
- [x] 유피넬 공식메일로 깃헙계정 만들기
- [ ] 유피넬 공식메일로 Gravatar 계정 만들어서 프사 등록하기
- [ ] 유피넬 도커헙 Org에 가서 깃헙계정 링크 바꾸고 프사 등록하기

**Comment by pbzweihander** [comment]
<upnl.chairman@gmail.com>으로 @upnl-snu 계정을 만들었습니다. 비밀번호는 others.md에 넣어놓았습니다.

**Comment by pbzweihander** [comment]
docker hub upnl org에 제 계정 연동을 끊고 upnl-snu 계정을 연동시켰습니다.

**Comment by pbzweihander** [comment]
Gravatar는 있으면 좋지만, 관리해야할 계정이 늘어나게 되는거 같아서 굳이 없어도 되지 않을까 싶네요
