### ISSUE TITLE
유피넬 공식 트위터 계정 탈취하기

### ISSUE THREAD

**Issue by simnalamburt** [upnl/work#5]
<https://twitter.com/__UPnL__>

잘 쓰던 트위터인데, 저거 트위터 계정 이메일 (아마도 <upnl@upnl.org>였음) 이 못쓰게되어서 지금 저 계정을 만질수가 없음.

### TODO
- [x] [@\_\_UPnL__](https://twitter.com/__UPnL__/status/1018891915222118400?s=19) 복구함
- [x] [@TeamBerryz](https://twitter.com/TeamBerryz) 복구함 
- [x] 넬장인 @pbzweihander, 부넬장인 @MKRoughDiamond, 서버관리자인 @tirr-c 에게 PGP로 비밀버호 전달함 https://pastebin.com/raw/1TjG1rEk

**Comment by jc-kim** [comment]
저거 마지막으로 관리하던 사람이 나인거 같은데[..] 비번이 기억나지 않습니다 ㅈㅅ...

**Comment by simnalamburt** [comment]
복구했습니다. [@\_\_UPnL__](https://twitter.com/__UPnL__/status/1018891915222118400?s=19)

**Comment by simnalamburt** [comment]
트위터에서 광고메일을 보내서 우연히 [@TeamBerryz](https://twitter.com/TeamBerryz)라는 계정이 있다는 사실을 알게되어, 저 메일도 복구했습니다.

**Comment by simnalamburt** [comment]
@tirr-c @pbzweihander @MKRoughDiamond 

두 트위터 계정의 비밀번호는 https://pastebin.com/raw/1TjG1rEk 와 같습니다.
