### ISSUE TITLE
제미니 AWS로 옮기기

### ISSUE THREAD

**Issue by simnalamburt** [upnl/work#50]
작년에 제미니가 하드웨어도 노후하고 정전사고도 한번 발생했었어서, 이를 AWS로 옮기기로 이미 결정했습니다. 아직 실행이 안된 상태인데, 슬슬 실행해봅시다.

### TODOs
- [x] AWS 계정 만들기 &rarr; @integraldx 님께서 처리해주심 https://github.com/upnl/work/commit/537e87274
- [x] AWS IAM 계정 만들기 (서버관리자만)
- [x] [Terraform Cloud] 회원가입하기, 2FA 켜기, `~/.terraformrc` 세팅
- [x] 팀 만들고 사람들 초대하기 &rarr; https://app.terraform.io/app/upnl/workspaces
- [x] 사람들 IAM User 액세스 시크릿 만듦
- [x] 서버관리자 Group 만들어 서버관리자 IAM들 소속시키고 관리자 권한 부여함
- [x] AWS 루트계정 액세스키 없애기
- [x] AWS 테라폼 세팅하기 → https://github.com/upnl/infra/
- [x] 제미니 만들기 → https://github.com/upnl/infra/pull/1
- [x] k3s 세팅하기
- [x] k3s에서 PVC 쓸 수 있게 하기
- [x] EBS PVC 대신 로컬 스토리지 PVC 쓰도록 수정하기
- 서비스들 옮겨오기
  - [x] https://upnl.org
  - [x] https://pokemon.upnl.org
  - [x] https://git.upnl.org
  - [x] https://helix.upnl.org
- [x] ECR 쓸 수 있도록 세팅하기 &rarr; https://github.com/upnl/work/issues/54
- [x] 지금까지 만든 백업들 AWS S3에 올리기
- [x] 컨테이너들 파일들 별도 EBS에 마운트하기 &rarr; https://github.com/upnl/kubernetes/commit/5fad771b7a612b8e9368f5bf9c07a72dda01a13a
- [x] RI/Saving Plan 구매 &rarr; https://github.com/upnl/work/issues/58
- [x] EC2에 터미네이션 프로텍션 걸기 &rarr; https://github.com/upnl/infra/commit/7446a893c27de4200f077dabd03d7ec6853beb51
- [x] 쿠버에서 사용하는 EBS들 자동으로 S3같은곳에 백업하게 만들고, S3에 라이프사이클 폴리시 걸기 &rarr; https://github.com/upnl/work/issues/40
- [x] [aws-iam-authenticator](https://github.com/kubernetes-sigs/aws-iam-authenticator) 쓰기 &rarr; https://github.com/upnl/work/issues/61
- [x] https://github.com/bitnami-labs/sealed-secrets 쓰기 &rarr; https://github.com/upnl/work/issues/61
- [x] https://sshcheck.com 테스트하기 &rarr; https://github.com/upnl/work/issues/60
- [x] TLS 세팅 제대로 하기, SSL Test A+ 맞기, TLS 1.3 지원 넣기, 위험한 사이퍼 끄기 &rarr; https://github.com/upnl/work/issues/62

[Terraform Cloud]: https://app.terraform.io/signup?utm_source=banner&utm_campaign=intro_tf_cloud_remote

제미니를 AWS로 옮긴 이후에 할 수 있는 일

- [x] AWS 루트계정에 MFA 걸기 &rarr; https://github.com/upnl/work/issues/59
- [x] AWS IAM 계정들에 MFA 강제하기 &rarr; https://github.com/upnl/work/issues/59
- [x] AWS IAM 유저그룹 만들기 (넬장/부넬장 그룹, 서버관리자 그룹, 정회원 그룹, 준회원 그룹, 등) &rarr; https://github.com/upnl/work/issues/59
- [x] AWS IAM 롤 만들기 (서버 추가삭제 권한 있는지 여부, 등) &rarr; https://github.com/upnl/work/issues/59
- [x] AWS EC2 Instance Connect 써서 회원들에게 서버 접근권한 나눠주기 https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Connect-using-EC2-Instance-Connect.html &rarr; https://github.com/upnl/work/issues/59

**Comment by simnalamburt** [comment]
2주 안에 해결해야할것같아요. 저 이사하기까지 시간이 얼마 안남았어요.

**Comment by simnalamburt** [comment]
2주 안에 해결해야할것같아요. 제미니를 꺼야하는 날이 얼마 안남았어요

**Comment by simnalamburt** [comment]
helix.upnl.org 의 upstart service 파일이었던 것입니다

```upstart
# /etc/init/helix.upnl.org.conf
description "Fossil Community"
start on (local-filesystems and net-device-up IFACE!=lo)
console log
setuid huu0909
setgid huu0909
respawn
respawn limit 10 5
chdir /home/huu0909/fossil_community
exec /home/huu0909/upnlwebenv/bin/uwsgi /home/huu0909/fossil_community/uwsgi.ini
```

**Comment by simnalamburt** [comment]
제미니 AWS 이전이 완료되었습니다. 남은 자잘한 할일들은 별도 이슈로 옮기겠습니다
