### ISSUE TITLE
AWS 서버에 이름 붙이기

### ISSUE THREAD

**Issue by simnalamburt** [upnl/work#56]
귀찮아서 기존 제미니를 "구 제미니"라고 부르고 AWS 서버 이름을 "신 제미니"라고 명명했더니 개판이 되었다.

"제미니"라는 이름은 2008년부터 2020년까지 유피넬에서 쓰였던 물리머신의 이름으로 고정하고, AWS 서버를 위한 이름은 새로 지어주자.

새 이름이 지어지면 upnl/infra 리포의 테라폼 코드를 비롯해 AWS 서버를 제미니라고 명명한 곳은 모두 고쳐야 한다.

### TODOs
- [x] 이름 짓기 &rarr; ebony
- 테라폼 코드에 새 이름인 ebony 반영하기
  - [x] https://github.com/upnl/infra/blob/d015dd3a/ec2.tf#L38 &rarr; Closed by https://github.com/upnl/infra/commit/d526f51bfc1cf51f6d657c5956d5428210ca1c4b
  - [x] https://github.com/upnl/infra/blob/d015dd3a/ec2.tf#L88 &rarr; Closed by https://github.com/upnl/infra/commit/4612958071a334d47734e3a7cef404d7e831d67e
  - [x] https://github.com/upnl/infra/blob/d015dd3a/iam.tf#L97 &rarr; Closed by https://github.com/upnl/infra/commit/477549f1bf9a5a908cc6012ef3fea69d3e3cd7bc
  - [x] https://github.com/upnl/infra/blob/d015dd3a/iam.tf#L104 &rarr; Closed by https://github.com/upnl/infra/commit/477549f1bf9a5a908cc6012ef3fea69d3e3cd7bc

**Comment by simnalamburt** [comment]
유피넬 전통인 “드래곤라자 소설 아무권 아무페이지를 펼쳐서 나오는 맨 첫 고유명사로 서버이름 짓기”에 따라, 드래곤라자 4권 13페이지 맨 앞에 나오는 네리아의 까만 말의 이름인 “에보니” (ebony, 에보니 나이트호크)로 결정됨.

![BD20C30C-AA4D-429D-A3CB-473530884C98](https://user-images.githubusercontent.com/4435445/75756145-7728b480-5d73-11ea-934e-b6d2b27665d1.jpeg)

**Comment by integraldx** [comment]
infra 코드에 반영했습니다.

**Comment by pbzweihander** [comment]
resource 이름 등은 변경했는데 IAM Role 이름 등에 아직 gemini가 남아있습니다.

**Comment by simnalamburt** [comment]
지금 아마 k3s가 AWS 권한을 아예 안쓰지 않나 싶은데.. 제미니로 이름지어진 인스턴스 프로필 걍 다 지워버릴까요 (?)

**Comment by simnalamburt** [comment]
https://github.com/upnl/infra/pull/7 때문에 필요하겠네요 ㅋㅋ

**Comment by simnalamburt** [comment]
작업 완료
