### ISSUE TITLE
AWS 서버 에델브로이로 이전하기

### ISSUE THREAD

**Issue by simnalamburt** [upnl/work#63]
꺼져서 접근이 안된다. 서버실 가서 켜야한다.

### TODOs
- [x] 에델브로이 부팅 성공시키기
- [x] 에델브로이 재설치하기
- [x] 다시 서버랙에 꽂기
- [x] 옆 실습컴에서 뽑은 랜선 복구시키기
- [x] 포트 열기 (메일 보냈음, 회신 대기중)
- [x] 인터넷 반복적으로 끊겼다가 됐다 하는 현상 해결하기. 아무래도 컴퓨터문제는 아닌것같아 메일 보냄, 회신 대기중
- [x] AWS에 저장되어있고 따로 백업되어있지 않던 도커이미지들 깃헙에 모두 올리기
- [x] 도커이미지들 경로 로컬이 아니라 GHCR을 가리키도록 YAML모두 고치고
- [x] Let's Encrypt 이슈어 대신 클라우드플레어 DNS-01 챌린지 쓰도록 고친다음
- [x] 에보니에서 위의 작업을 모두 적용시켜도 정상동작하는걸 확인
- [x] 포디비에 robots.txt 및 각종 수정한것 배포하여 정상동작 확인
- [x] AWS에서 에델브로이로 state와 yaml을 모두 한방에 가져온다
- [x] AWS 정리
- 백업봇에 AWS 권한 부여 &rarr; #68

**Comment by simnalamburt** [comment]
부트디바이스가 안잡혀서 부팅이 안됨. 디버깅이 필요함

###### Reference
- https://upnl-snu.slack.com/archives/CCC0XG5V5/p1587021124117400

**Comment by simnalamburt** [comment]
재정문제로 AWS를 없애기로함. 에델브로이를 빠르게 되살릴 필요가 생겼다.

<img width=400 src="https://user-images.githubusercontent.com/4435445/108059675-349ddc00-7099-11eb-9ca1-0f986edba24e.png">

서버랙에서 꺼냈음, OS를 못찾아 부팅 못하는것 확인, 우분투 20.04.2 설치 시도중, 디스크 문제가 있을경우를 대비해 새 SSD도 준비된 상태. 새 SSD를 쓰게되면 부품값은 미래에 넬에서 지원해주기로했음.

**Comment by simnalamburt** [comment]
기존 SSD(Samsung SSD 830)의 고장을 확인함. 갖고있던 다른 SSD(Samsung SSD 840 PRO)로 교체중.

**Comment by simnalamburt** [comment]
다시 확인한 결과 기존 SSD(Samsung SSD 830)이 고장난것은 아니었음. 그러나 과거 오랫동안 활발하게 사용되었던 전력이 있는 SSD여서 수명이 걱정되어 그냥 바꾸기로했다.

**Comment by simnalamburt** [comment]
OS 설치 완료, 시스템 세팅중. 포트들이 죄다 막혀있어 정상적인 작업이 어렵다.

**Comment by simnalamburt** [comment]
22, 80, 443, 2222 포트에 대한 개방요청 완료, 회신 대기중

**Comment by simnalamburt** [comment]
DNS 리졸빙이 임의로 실패하는 등, 정보화본부(중앙전산원)에서 자꾸 DNS 트래픽을 가로채는듯한 동작을 보임. 이에 따라, 모든 암호화되지 않은 트래픽은 학교가 가로채는것으로 가정하고 `cloudflared`를 사용해 DNS-over-HTTPS를 사용하도록 세팅함.

**Comment by simnalamburt** [comment]
아직 할일이 남긴했지만 서버를 대충 띄우긴 했는데, TCP 연결이 무수히 임의로 끊기는 등 네트워크 상태가 몹시 좋지않음. 근데 이것이 컴퓨터의 문제인지 아니면 학교 전산망의 문제인지 현재 구분이 안간다.

**Comment by simnalamburt** [comment]
서버랙으로 옮기자 인터넷이 전혀 안됨.

**Comment by simnalamburt** [comment]
스위치 포트를 옮겼더니 이제 인터넷이 아예 안되지는 않으나 여전히 연결에 성공했다 실패했다를 반복중임. 지은상 선생님께 문의함.

**Comment by simnalamburt** [comment]
현재 남은 문제인 인터넷 문제와 포트 개방 문제 모두 행정실 도움 없이 해결 불가능할것같아 작업 중단.

**Comment by tirr-c** [comment]
MAC주소-IP주소가 중전에 등록이 안되어있으면 패킷 로스가 심합니다.

**Comment by simnalamburt** [comment]
기존 IP는 타 서버에 의해 선점당함, 신규 발급 신청함, 회신 대기중

2021년 2월 17일 (수) 10:30, Wonwoo Choi <notifications@github.com>님이 작성:

**Comment by simnalamburt** [comment]
> 안녕하세요. 서울대 정보화지원과(정보보안)입니다.
> 웹취약점 점검은 개발이 완료된 홈페이지의 취약점을 분석하고 개선할 수 있도록 진행되어야 합니다.
> 현재 edhelbroy.upnl.org홈페이지 개발 완료된 것인지 확인요청드립니다.
> 만약 홈페이지 개발중인 단계라면 개발 완료 후 웹취약점 재점검 및 조치 바랍니다.
> 감사합니다.

서비스다운게 올라와야 점검을 할 수 있다고 함

**Comment by simnalamburt** [comment]
에델브로이에 k3s 사용해 포디비 배포한 뒤 다시 포트개방 신청했음. 정보화본부에서 퍼징을 돌려서 포디비의 잠재적 문제를 몇가지 찾아냈다. 조치하여 오늘 다시 열어달라고 지은상선생님께 메일 보냈음.

**Comment by simnalamburt** [comment]
> 포트(웹서비스용) 오픈 이후 연 1회 이상 통합취약점관리시스템에 접속하여 홈페이지 담당자가 직접 취약점 점검/개선하여야 합니다.

아놔..

**Comment by tirr-c** [comment]
맞아요 저거 귀찮아요... 바쿠스에서 매년 하는거긴한데 다들 드르렁

**Comment by tirr-c** [comment]
http://edhelbroy.upnl.org/ 열렸습니다.

state 복사는 서버 내리고 rsync를 사용하기로

**Comment by simnalamburt** [comment]
모든 서비스들 에델브로이로 이전 완료, AWS 자원 정리중

**Comment by simnalamburt** [comment]
완료
